### ISSUE TITLE
Uncaught RangeError: Mark decorations may not be empty

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/alifstudio3#4]
<div dir="rtl">

`اطبعfoo("مرحبا!" + سطر)` --> `السطر 5: أمر غير معروف : ' اطبعfoo '` -> `خطأ(..)`

<div dir="ltr">

```
Uncaught RangeError: Mark decorations may not be empty
    at lt.range (index.js:1044)
    at error-extension.js:57
    at Array.map (<anonymous>)
    at c (error-extension.js:50)
    at Object.k [as خطأ] (index.js:121)
    at alif_debug_json (index.html?webui=http://127.0.0.1:8081/webuicore.js:212)
    at eval (eval at <anonymous> (webuicore.js:139), <anonymous>:3:1)
    at FileReader.<anonymous> (webuicore.js:141)
```

**Comment by assawalhy** [comment]
<div dir=rtl>

الدالة `خطأ` تحتاج لوسيطين أن يرسلا، `lineNumber`، `errorDescription`:

<div dir=ltr>

```js
export function خطأ(lineNumber, errorDescription) {
  // Show an error in Codemirror
  // Link: https://codemirror.net/6/docs/migration/
  // Section: Marked Text
  addErrors([{ line: lineNumber, msg: errorDescription }], editor);
}
```

</div>

**Comment by hassandraga** [comment]
<div dir=rtl>
أسف، لكن هته أمور بديهية، أقصد واضحة

https://github.com/alifcommunity/alifstudio3/blob/7f6839dc57ea41676a82466a07bc825836bcb005/index.html#L212

المشكلة في شيء آخر.

**Comment by assawalhy** [comment]
<div dir=rtl>

جرب رؤية ما يتم تمريره عن طريق `console`

</div>

```js
export function خطأ(lineNumber, errorDescription) {
  // Show an error in Codemirror
  // Link: https://codemirror.net/6/docs/migration/
  // Section: Marked Text
  console.log({ line: lineNumber, msg: errorDescription });
  addErrors([{ line: lineNumber, msg: errorDescription }], editor);
}
```

**Comment by hassandraga** [comment]
<div dir=rtl>

هذا هو اول شيء بدأت به
حتى تمرير الداتا مباشرة 
مثلا 
( 2, 'تجربة' )

عموما، واجهتني هته المشكلة كذالك في الف ستوديو ٢ 
كنت أستخدم santilla ب C++
الحل هو كان هو إزالة ال marker
و تسجيل جديد عند كل خطأ جديد

**Comment by hassandraga** [comment]
<div dir=rtl>

مازال المشكل موجود بعد التحديث
الأداة تحتاج لمعرفة طول السطر الذي يحتوي على الخطأ
ال `range` دائما غير صحيحة

**Comment by assawalhy** [comment]
أظن أن للأمر علاقة بحذف حرفين في نفس الوقت، أرجو أن تصور لي الشاشة فيديو وأنت تتبع خطوات معينة لتحدث هذه المشكلة بحيث استطيع إعادة توليد الخطأ عندي ومحاولة حله.

**Comment by hassandraga** [comment]
![alifstudio3_error](https://user-images.githubusercontent.com/16948659/124784422-eab47600-df13-11eb-89ce-24204e415d48.png)

**Comment by hassandraga** [comment]
![alifstudio3_error_fix](https://user-images.githubusercontent.com/16948659/124784849-53035780-df14-11eb-88d6-598ffad9266a.png)

**Comment by hassandraga** [comment]
<div dir=rtl>

المشكل فقط في الحروف العربية
في ترميز `ASCII` كل حرف هو واحد بايث
لكن في `UTF8` قد يكون واحد، وقد يكون أربعة.

**Comment by hassandraga** [comment]
> CodeMirror does no character encoding or decoding at all (it gets all
> its strings from JS and the DOM)

**Comment by assawalhy** [comment]
![image](https://user-images.githubusercontent.com/42011920/124886940-3e7e9800-dfc4-11eb-9ff6-a3bab90ae5a7.png)

**Comment by assawalhy** [comment]
![image](https://user-images.githubusercontent.com/42011920/124886992-49d1c380-dfc4-11eb-8d34-54d42107caf5.png)
